name    'dmexe-rbenv'
version '0.1.1'
source 'git://github.com/dima-exe/puppet-rbenv.git'
author 'Dmitry Galinsky'
license 'MIT'
summary 'Puppet for rbenv'
project_page 'http://github.com/dima-exe/puppet-rbenv'
