name    'dmexe-rbenv'
version '0.1.0'
source 'http://github.com/dima-exe/puppet-rbenv'
author 'Dmitry Galinsky'
license 'MIT'
summary 'Puppet for rbenv'
project_page 'http://github.com/dima-exe/puppet-rbenv'
